### ISSUE TITLE
WinRM support

### ISSUE THREAD

**Issue by adpande** [eBay/parallec#26]
Hi
It would be wonderful to see winrm support to execute command on Windows servers.

Regards,
Abhishek

**Comment by jeffpeiyt** [comment]
Hi Abhishek,

Thanks very much for your interests and suggestion on Parallec.

not familiar with winrm.  From https://github.com/bmoussaud/WinRM , it said `The Windows Remote Management (WinRM) is the Microsoft implementation of WS-Management Protocol, a standard Simple Object Access Protocol (SOAP)-based, firewall-friendly protocol that allows hardware and operating systems, from different vendors, to interoperate.`

Thus, it looks like a wrapper protocol based on SOAP, which is XML just based on HTTP(S). If you can intercept the actual message in XML.  Wonder could you please trying to send the raw XML content (which is essentially SOAP) in HTTP?

**Comment by jeffpeiyt** [comment]
it seems possible to integrate Parallec with the  overthere `WinRmClient` : http://xebialabs.github.io/overthere/javadoc/com/xebialabs/overthere/cifs/winrm/WinRmClient.html

However this may not be the focus for Parallec now due to this protocol's popularity in current cloud system...  feel free to submit a pull request or work on this and that would be great. 


From http://www.masterzen.fr/2014/01/11/bootstrapping-windows-servers-with-puppet/: 

One component of WinRM is WinRS: Windows Remote Shell. This is the part that allows to run remote commands. Recent Windows version (at least since Server 2003) are shipped with WinRM installed (but not started by default).

WinRM is an HTTP/SOAP based protocol. By default, the payload is encrypted if the protocol is used in a Domain Controller environment (in this case, it uses Kerberos), which will not be our case on EC2.

**Comment by jeffpeiyt** [comment]
Close the ticket as there is no further discussion.
